name: build
on:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: Documentation
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs
      - run: pip install mkdocs-material
      - run: pip install mike
      - run: mike deploy --push --update-aliases 0.1 latest
      - run: mkdocs gh-deploy --force --clean --verbose
